# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# --- al-folio theme setup ---
remote_theme: alshedivat/al-folio@v1.7.0
plugins:
  - jekyll-remote-theme
# -------------------------------

title:       "Gabe da Hora, Ph.D."
description: "Computational chemist | Postdoctoral Research Associate @ University of Utah"
url:         "https://gabedahora.com"

author:
  name:      "Gabriel Costa A. da Hora"
  avatar:    "/images/profile-20231018.jpg"
#  email:     "seu-email@exemplo.com"
  github:    "gabedahora"
  linkedin:  "gabriel-costa-da-hora"
  orcid:     "0000-0002-6372-6533"
  googlescholar: "zY6BDnIAAAAJ" 

nav:
  - title: Home
    url:   /
  - title: News
    url:   /#news
  - title: Research
    url:   /#research
  - title: Publications
    url:   /#publications
  - title: Teaching
    url:   /#teaching
  - title: Contact
    url:   /contact/
